In [71]:
!pip install numpy pandas matplotlib seaborn scikit-learn nltk

Requirement already satisfied: numpy in c:\fakejobposting\.venv\lib\site-packages (2.4.3)
Requirement already satisfied: pandas in c:\fakejobposting\.venv\lib\site-packages (3.0.1)
Requirement already satisfied: matplotlib in c:\fakejobposting\.venv\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\fakejobposting\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\fakejobposting\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: nltk in c:\fakejobposting\.venv\lib\site-packages (3.9.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\fakejobposting\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\fakejobposting\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\fakejobposting\.venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\fakejobposting\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\fakejobposting\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\fakejobposting\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in c:\fakejobposting\.venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in c:\fakejobposting\.venv\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\fakejobposting\.venv\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in c:\fakejobposting\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\fakejobposting\.venv\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
import pandas as pd

df=pd.read_csv('fake_job_postings.csv')
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  str
 2   location             17534 non-null  str
 3   department           6333 non-null   str
 4   salary_range         2868 non-null   str
 5   company_profile      14572 non-null  str
 6   description          17879 non-null  str
 7   requirements         15184 non-null  str
 8   benefits             10668 non-null  str
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  str
 13  required_experience  10830 non-null  str
 14  required_education   9775 non-null   str
 15  industry             12977 non-null  str
 16  function             11425 non-null  str
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), str(13)
memory usage: 2.5 MB

In [73]:
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [74]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\vansh
[nltk_data]     tanwar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\vansh
[nltk_data]     tanwar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\vansh
[nltk_data]     tanwar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [75]:
text_cols = ['title','description','requirements','benefits','company_profile']

df['text'] = df[text_cols].fillna('').agg(' '.join, axis=1)

In [76]:
df['text'].head()

0    Marketing Intern Food52, a fast-growing, James...
1    Customer Service - Cloud Video Production Orga...
2    Commissioning Machinery Assistant (CMA) Our cl...
3    Account Executive - Washington DC THE COMPANY:...
4    Bill Review Manager JOB TITLE: Itemization Rev...
Name: text, dtype: str

In [77]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

corpus = []

for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if word not in stop_words]

    review = " ".join(review)
    corpus.append(review)

In [78]:
len(corpus)

17880

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=10000)
X = tv.fit_transform(corpus).toarray()

In [80]:
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,"Marketing Intern Food52, a fast-growing, James..."
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,Customer Service - Cloud Video Production Orga...
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,Commissioning Machinery Assistant (CMA) Our cl...
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,Account Executive - Washington DC THE COMPANY:...
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,Bill Review Manager JOB TITLE: Itemization Rev...

In [81]:
print(df['telecommuting'].isnull().sum())
print(df['has_company_logo'].isnull().sum())
print(df['has_questions'].isnull().sum())
print(df['fraudulent'].isnull().sum())

0
0
0
0

In [82]:
df['salary_range'].unique()

<StringArray>
[            nan,   '20000-28000', '100000-120000', '120000-150000',
   '50000-65000',   '40000-50000',         '60-80',   '65000-70000',
        '75-115',  '75000-110000',
 ...
        'Dec-25',     '1517-1517',    '1234-12345',   '34000-42000',
         '15-19',         '21-31',   '48000-65000',   '53000-67000',
      '22-61000',     '3700-3800']
Length: 875, dtype: str

In [83]:
df[['min_salary','max_salary']] = df['salary_range'].str.split('-', expand=True)

df['min_salary'] = pd.to_numeric(df['min_salary'], errors='coerce')
df['max_salary'] = pd.to_numeric(df['max_salary'], errors='coerce')

df['avg_salary'] = (df['min_salary'] + df['max_salary']) / 2

df['avg_salary'] = df['avg_salary'].fillna(0)

df.drop(['salary_range','min_salary','max_salary'], axis=1, inplace=True)

In [84]:
df.drop(['job_id','title','description','requirements','benefits','company_profile'], axis=1, inplace=True)
df.head()

,location,department,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text,avg_salary
0,"US, NY, New York",Marketing,0,1,0,Other,Internship,NaN,NaN,Marketing,0,"Marketing Intern Food52, a fast-growing, James...",0.0
1,"NZ, , Auckland",Success,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,Customer Service - Cloud Video Production Orga...,0.0
2,"US, IA, Wever",NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,Commissioning Machinery Assistant (CMA) Our cl...,0.0
3,"US, DC, Washington",Sales,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,Account Executive - Washington DC THE COMPANY:...,0.0
4,"US, FL, Fort Worth",NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,Bill Review Manager JOB TITLE: Itemization Rev...,0.0

In [85]:
df['avg_salary'].unique()

array([0.000000e+00, 2.400000e+04, 1.100000e+05, 1.350000e+05,
       5.750000e+04, 4.500000e+04, 7.000000e+01, 6.750000e+04,
       9.500000e+01, 9.250000e+04, 1.850000e+04, 2.200000e+04,
       1.050000e+05, 1.650000e+04, 6.000000e+04, 5.250000e+04,
       3.500000e+04, 8.000000e+04, 1.200000e+04, 8.000000e+01,
       3.650000e+04, 1.715000e+04, 3.750000e+04, 5.050000e+04,
       2.325000e+04, 6.500000e+04, 3.250000e+04, 3.000000e+04,
       4.800000e+05, 9.000000e+04, 1.575000e+04, 4.750000e+04,
       3.350000e+04, 5.600000e+04, 1.980000e+05, 5.500000e+04,
       5.000000e+02, 3.800000e+04, 9.500000e+04, 5.400000e+04,
       1.900000e+04, 7.560000e+06, 4.850000e+04, 1.250000e+05,
       3.300000e+04, 1.650000e+03, 5.000000e+04, 3.600000e+04,
       7.500000e+01, 1.300000e+04, 2.592000e+04, 1.075000e+02,
       1.450000e+04, 1.400000e+05, 1.050000e+04, 7.000000e+04,
       6.750000e+05, 1.450000e+05, 2.750000e+04, 1.150000e+05,
       2.600000e+04, 5.500000e+03, 4.400000e+04, 1.100000e+04,
       1.300000e+05, 1.000000e+05, 3.500000e+05, 1.080000e+04,
       6.100000e+04, 9.750000e+04, 3.700000e+04, 2.000000e+04,
       1.425000e+05, 1.950000e+04, 2.000000e+05, 7.250000e+04,
       6.250000e+04, 3.350000e+05, 2.300000e+04, 1.380000e+04,
       3.400000e+04, 1.050000e+02, 5.000500e+03, 5.150000e+05,
       4.000000e+04, 2.500000e+04, 2.100000e+05, 8.750000e+01,
       1.161000e+03, 4.200000e+04, 4.000000e+01, 1.750000e+04,
       1.725000e+04, 1.200000e+05, 4.250000e+04, 3.150000e+04,
       4.950000e+04, 7.500000e+04, 2.495000e+05, 5.150000e+01,
       3.450000e+04, 2.800000e+04, 3.360000e+04, 4.300000e+04,
       1.125000e+02, 8.000000e+03, 7.750000e+04, 4.500000e+03,
       8.500000e+01, 3.000000e+03, 2.250000e+04, 2.556000e+04,
       5.280000e+04, 9.300000e+04, 5.750000e+05, 8.500000e+04,
       1.650000e+01, 1.500000e+03, 1.125000e+05, 1.500000e+04,
       1.600000e+04, 6.105850e+04, 3.151050e+04, 1.700000e+04,
       2.150000e+04, 1.250000e+04, 3.275000e+04, 1.800000e+05,
       2.900000e+04, 2.550000e+04, 5.450000e+04, 4.919400e+04,
       1.560000e+04, 1.600000e+03, 3.050000e+04, 9.000000e+03,
       1.500000e+02, 1.150000e+03, 9.800000e+04, 3.100000e+04,
       1.800000e+04, 1.075000e+03, 2.100000e+04, 1.005000e+04,
       5.250000e+05, 1.400000e+06, 3.675000e+05, 1.000000e+03,
       1.080000e+06, 6.000000e+01, 5.950000e+04, 5.400000e+05,
       1.275000e+05, 8.750000e+04, 2.805000e+04, 2.050000e+04,
       1.339500e+04, 4.680000e+06, 1.340000e+02, 3.740000e+04,
       5.350000e+04, 1.550000e+04, 1.500000e+05, 6.950000e+04,
       9.950000e+04, 1.547500e+03, 3.900000e+04, 1.000000e+09,
       5.200000e+04, 2.450000e+04, 1.850000e+05, 8.700000e+04,
       2.000000e+01, 3.375000e+04, 5.500000e+01, 2.030000e+04,
       1.350000e+04, 8.250000e+04, 5.000000e-01, 4.000000e+05,
       1.375000e+04, 3.150000e+05, 4.050000e+04, 2.350000e+04,
       2.028000e+04, 5.000000e+05, 6.850000e+04, 6.300000e+05,
       8.200000e+04, 3.900000e+05, 1.612000e+04, 4.750000e+02,
       2.250000e+01, 3.500000e+03, 3.016000e+04, 1.175000e+05,
       2.400000e+05, 1.760000e+04, 6.500000e+01, 1.400000e+01,
       7.500000e+03, 6.000000e+05, 2.700000e+04, 2.150000e+02,
       5.150000e+04, 2.850000e+04, 7.505000e+05, 4.600000e+04,
       1.075000e+05, 1.700000e+05, 3.750000e+03, 1.250000e+02,
       4.000000e+03, 1.225000e+05, 2.000000e+03, 4.250000e+05,
       3.500000e+06, 2.650000e+04, 1.375000e+05, 7.424352e+06,
       2.600000e+05, 1.025000e+05, 4.100000e+04, 1.000000e+06,
       3.328000e+04, 6.750000e+01, 7.050000e+04, 1.250000e+03,
       1.325000e+04, 6.936000e+05, 1.900000e+05, 1.000000e+04,
       2.184000e+04, 1.400000e+04, 1.475000e+04, 3.350000e+01,
       7.500000e+02, 3.750000e+01, 7.000000e+05, 2.180000e+04,
       2.850000e+01, 3.750000e+05, 2.950000e+04, 9.000000e+01,
       6.500000e+05, 1.150000e+02, 2.100000e+01, 3.175000e+04,
       3.125000e+05, 3.700000e+05, 2.175000e+04, 5.125000e+02,
       2.640000e+04, 4.650000e+01, 1.180000e+05, 9.000000e+02,
       1.750000e+05, 3.150000e+03, 1.100000e+02, 1.550000e+05,
       8.500000e+06, 6.500000e+06, 2.250000e+05, 1.820000e+04,
       2.250000e+02, 1.165000e+05, 4.750000e+01, 8.640000e+04,
       3.850000e+04, 3.200000e+04, 2.130000e+05, 8.325000e+06,
       6.650000e+04, 1.850000e+01, 2.580000e+04, 4.500000e+01,
       3.591390e+05, 9.000000e+05, 1.085000e+05, 1.920000e+04,
       2.450000e+01, 2.750000e+05, 2.000000e+02, 1.400000e+02,
       2.650000e+01, 8.000000e+05, 3.536000e+04, 6.000000e+03,
       1.110000e+05, 8.450000e+04, 1.450000e+01, 1.924000e+04,
       3.550000e+04, 2.050000e+05, 2.000000e+06, 9.500000e+05,
       1.080000e+05, 9.949950e+04, 6.150000e+04, 1.550000e+06,
       4.700000e+04, 4.800000e+04, 2.225000e+05, 5.520300e+04,
       5.000000e+03, 1.800000e+01, 1.920000e+05, 2.500000e+05,
       1.000000e+02, 9.250000e+02, 9.500000e+03, 1.050000e+06,
       1.050000e+03, 4.150000e+04, 2.275000e+04, 3.500000e+01,
       7.150000e+04, 2.200000e+05, 9.500000e+02, 3.472000e+04,
       1.200000e+06, 9.560000e+02, 4.350000e+04, 2.700000e+05,
       3.600000e+05, 1.625000e+02, 5.100000e+04, 2.125000e+05,
       7.800000e+04, 6.600000e+04, 6.350000e+05, 1.122000e+04,
       4.680000e+04, 6.700000e+04, 9.750000e+05, 4.550000e+04,
       4.500000e+05, 2.100000e+03, 7.900000e+04, 6.500000e+08,
       2.500000e+03, 7.300000e+04, 2.131500e+06, 1.680000e+05,
       2.250000e+03, 3.437350e+04, 1.650000e+05, 3.064000e+04,
       1.400000e+03, 7.200000e+05, 3.120000e+04, 6.250000e+01,
       1.300000e+03, 7.250000e+01, 8.250000e+01, 5.820000e+05,
       7.004500e+04, 1.175000e+02, 5.750000e+01, 9.620000e+02,
       2.650000e+03, 9.650000e+04, 1.250000e+06, 4.580000e+04,
       1.120000e+05, 6.300000e+04, 3.930000e+04, 7.600000e+04,
       1.205000e+05, 7.750000e+03, 7.100000e+04, 1.960000e+03,
       5.850000e+04, 1.200000e+03, 6.003500e+03, 3.950000e+04,
       2.121800e+04, 3.535000e+04, 5.000000e+01, 3.000000e+01,
       5.650000e+04, 4.050000e+05, 5.300000e+04, 1.872000e+04,
       1.030000e+04, 1.440000e+05, 6.250000e+03, 2.500000e+01,
       4.200000e+05, 1.200000e+02, 3.250000e+01, 1.705600e+05,
       1.664000e+05, 2.132000e+05, 3.000000e+05, 1.081600e+05,
       8.500000e+03, 2.392000e+05, 3.800000e+05, 9.880000e+04,
       1.040000e+05, 1.716000e+05, 1.600000e+01, 6.350000e+01,
       5.600000e+01, 6.100000e+01, 5.400000e+01, 2.080000e+04,
       1.675000e+04, 6.200000e+04, 4.300000e+05, 4.750000e+03,
       2.750000e+01, 1.517000e+03, 6.789500e+03, 1.700000e+01,
       2.600000e+01, 3.051100e+04])

In [86]:
df.columns

Index(['location', 'department', 'telecommuting', 'has_company_logo',
       'has_questions', 'employment_type', 'required_experience',
       'required_education', 'industry', 'function', 'fraudulent', 'text',
       'avg_salary'],
      dtype='str')

In [88]:
# split location into country, state, city
loc = df['location'].str.split(',', n=2, expand=True)

df['country'] = loc[0]
df['state'] = loc[1]
df['city'] = loc[2]

# fill missing values
df[['country','state','city']] = df[['country','state','city']].fillna('unknown')

# encode
from sklearn.preprocessing import LabelEncoder

for col in ['country','state','city']:
    df[col] = LabelEncoder().fit_transform(df[col])

# drop original column
df.drop('location', axis=1, inplace=True)

In [89]:
from sklearn.preprocessing import LabelEncoder

cols = ['department','employment_type','required_experience',
        'required_education','industry','function']

le = LabelEncoder()

for col in cols:
    df[col] = df[col].astype(str)
    df[col] = le.fit_transform(df[col])

In [90]:
df.head()

,department,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text,avg_salary,country,state,city
0,758,0,1,0,2,4,13,131,22,0,"Marketing Intern Food52, a fast-growing, James...",0.0,85,228,1458
1,1161,0,1,0,1,6,13,75,7,0,Customer Service - Cloud Video Production Orga...,0.0,60,0,189
2,1337,0,1,0,5,7,13,131,37,0,Commissioning Machinery Assistant (CMA) Our cl...,0.0,85,156,2213
3,1054,0,1,0,1,5,1,22,31,0,Account Executive - Washington DC THE COMPANY:...,0.0,85,105,2164
4,1337,0,1,1,1,5,1,51,16,0,Bill Review Manager JOB TITLE: Itemization Rev...,0.0,85,131,787